### ISSUE TITLE
GraphMachine cannot plot states with transitions to themselves

### ISSUE THREAD

**Issue by chaosentity** [tyarkoni/transitions#133]
Using: 
Windows 10 64 bit
python 2.7.6 32-bit 
transitions 0.4.1
pygraphviz 1.3.1
graphviz 2.38

I've noticed that if a state machine has a state that can transition to the same state (e.g., state_1 can transition to state_1), pygraphviz encounters an error while trying to plot the state machine using GraphMachine

```python
from transitions.extensions import GraphMachine

states = ['first', 'second', 'last']
transitions = [
    {'trigger': 'move', 'source': 'first', 'dest': 'second'},
    {'trigger': 'go', 'source': 'second', 'dest': 'last'},
    {'trigger': 'end', 'source': 'last', 'dest': 'first'},
    # Uncommenting the following line causes an error in pygraphviz
    # {'trigger': 'nope', 'source': 'first', 'dest': 'first'},
]

class Basic(object): pass

machine = GraphMachine(model=Basic,
                       states=states,
                       transitions=transitions,
                       initial='first',
                       auto_transitions=False,
                       show_conditions=True,
                       )

machine.graph.draw('fsm.png', prog='dot')
```

Uncommenting the 4th transition leads to this error in pygraphviz:
```python
Traceback (most recent call last):
  File "C:/Users/James/PycharmProjects/cmwhitneytest/durrdurrdurr.py", line 24, in <module>
    show_conditions=True,
  File "C:\Python27\lib\site-packages\transitions\extensions\diagrams.py", line 176, in __init__
    super(GraphMachine, self).__init__(*args, **kwargs)
  File "C:\Python27\lib\site-packages\transitions\core.py", line 364, in __init__
    self.add_transition(**t)
  File "C:\Python27\lib\site-packages\transitions\extensions\diagrams.py", line 213, in add_transition
    self.graph = self.get_graph(force_new=True)
  File "C:\Python27\lib\site-packages\transitions\extensions\diagrams.py", line 188, in get_graph
    self.graph = AGraph(self).get_graph(title)
  File "C:\Python27\lib\site-packages\transitions\extensions\diagrams.py", line 154, in get_graph
    self._add_edges(self.machine.events, fsm_graph)
  File "C:\Python27\lib\site-packages\transitions\extensions\diagrams.py", line 122, in _add_edges
    container.add_edge(src.name, dst.name, label=edge_label, ltail=ltail, lhead=lhead)
  File "C:\Python27\lib\site-packages\pygraphviz\agraph.py", line 481, in add_edge
    eh = gv.agedge(self.handle, uh, vh, key, _Action.find)
KeyError: 'agedge: no key'
```

**Comment by wtgee** [comment]
Works in python 3+ with same versions of graphviz and pygraphviz. I'll check out python 2.7 a little later.

![fsm](https://cloud.githubusercontent.com/assets/70736/17988431/8d65087a-6b69-11e6-8650-4beb54951149.png)

**Comment by wtgee** [comment]
Also works on pyhon2.7.12 with same library version numbers. I'm not able to test on a windows machine at this time. 

Searching for that error message yields a bunch of people with the same problem and it seems to be traceable to something within pygraphviz so I'm afraid you'll have to go looking there for a solution. Closing for now.
