### ISSUE TITLE
pip install fails with transitions 0.2.6

### ISSUE THREAD

**Issue by njouanin** [tyarkoni/transitions#20]
Hi,
Here's the pip output when trying to install last transistions version (0.2.6):

    Downloading/unpacking transitions from https://pypi.python.org/packages/source/t/transitions/transitions-0.2.6.tar.gz#md5=c53bdddd361634a91c8b229c936e7e90 (from -r requirements.txt (line 1))
      Downloading transitions-0.2.6.tar.gz
      Running setup.py (path:/Users/nico/Dev/beerfactory/python/env-mqtt/build/transitions/setup.py) egg_info for package transitions
        Traceback (most recent call last):
          File "<string>", line 17, in <module>
          File "/Users/nico/Dev/beerfactory/python/env-mqtt/build/transitions/setup.py", line 4, in <module>
            from transitions.version import __version__
          File "/Users/nico/Dev/beerfactory/python/env-mqtt/build/transitions/transitions/__init__.py", line 2, in <module>
            from .core import (State, Transition, Event, EventData, Machine, MachineError,
          File "/Users/nico/Dev/beerfactory/python/env-mqtt/build/transitions/transitions/core.py", line 8, in     <module>
            from six import string_types
        ImportError: No module named 'six'
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):

      File "<string>", line 17, in <module>
    
      File "/Users/nico/Dev/beerfactory/python/env-mqtt/build/transitions/setup.py", line 4, in <module>
    
        from transitions.version import __version__
    
      File "/Users/nico/Dev/beerfactory/python/env-mqtt/build/transitions/transitions/__init__.py", line 2, in <module>
    
        from .core import (State, Transition, Event, EventData, Machine, MachineError,

      File "/Users/nico/Dev/beerfactory/python/env-mqtt/build/transitions/transitions/core.py", line 8, in <module>
    
        from six import string_types
    
    ImportError: No module named 'six'

**Comment by tyarkoni** [comment]
Thanks for catching this! I bumped the version and it should work in 0.2.7 from PyPI now.

**Comment by njouanin** [comment]
0.2.7 installed successfully.
