### ISSUE TITLE
Crash following README.md transitions-0.5.0 and 0.5.1

### ISSUE THREAD

**Issue by dgtlmoon** [tyarkoni/transitions#201]
From the README.md https://github.com/tyarkoni/transitions#ordered-transitions
```
from transitions import Machine

states = ['A', 'B', 'C']
 # See the "alternative initialization" section for an explanation of the 1st argument to init
machine = Machine(states, initial='A')
machine.add_ordered_transitions()
machine.next_state()
print(machine.state)

```

0.5.0 gives me
```

Traceback (most recent call last):
  File "state-test.py", line 5, in <module>
    machine = Machine(states, initial='A')
  File "/usr/local/lib/python3.5/dist-packages/transitions/core.py", line 463, in __init__
    self.add_model(model)
  File "/usr/local/lib/python3.5/dist-packages/transitions/core.py", line 482, in add_model
    model.trigger = partial(get_trigger, model)
AttributeError: 'str' object has no attribute 'trigger'
```

0.5.1 just built from a clone of the repo gives me

```
Traceback (most recent call last):
  File "state-test.py", line 5, in <module>
    machine = Machine(states, initial='A')
  File "/usr/local/lib/python3.5/dist-packages/transitions-0.5.1-py3.5.egg/transitions/core.py", line 465, in __init__
  File "/usr/local/lib/python3.5/dist-packages/transitions-0.5.1-py3.5.egg/transitions/core.py", line 484, in add_model
AttributeError: 'str' object has no attribute 'trigger'

```

I am on python 3.5.2, is there some documentation missing or is this a bug that's stopping people from using this library?

**Comment by aleneum** [comment]
Hi @dgtlmoon,

thats an error in the ReadMe. The first argument of `Machine`'s constructor should be the model, not the states. 
Changing `machine = Machine(states, initial='A')` to `machine=Machine(states=states, initial='A')` does the trick.

Thank you for the report. I will fix it instantly.

**Comment by dgtlmoon** [comment]
Glad to help! This is a great project, thanks! resolved the issue for me.
