### ISSUE TITLE
When a trigger is called, and the after/before callback has an exception, the state is still transitioned

### ISSUE THREAD

**Issue by dgtlmoon** [tyarkoni/transitions#202]
I have two states, game_begin and game_end, and i'm missing the implementation of `def do_stuff():`

```
>>> x.state
'game_begin'
>>> x.my_trigger()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/transitions-0.5.1-py3.5.egg/transitions/core.py", line 282, in trigger
  File "/usr/local/lib/python3.5/dist-packages/transitions-0.5.1-py3.5.egg/transitions/core.py", line 831, in _process
  File "/usr/local/lib/python3.5/dist-packages/transitions-0.5.1-py3.5.egg/transitions/core.py", line 312, in _trigger
  File "/usr/local/lib/python3.5/dist-packages/transitions-0.5.1-py3.5.egg/transitions/core.py", line 201, in execute
  File "/usr/local/lib/python3.5/dist-packages/transitions-0.5.1-py3.5.egg/transitions/core.py", line 809, in _callback
AttributeError: 'GameState' object has no attribute 'do_stuff'

>>> x.state
'game_complete'


```

**Comment by aleneum** [comment]
If an exception occurs *before* the transition (in prepare, before), it is halted. In case there is a raise *after* the transition has been conducted (in after, finalize), there is no rollback but the execution of further after callback is halted. If the error occurs in *after* callbacks, finalize callbacks will be executed though. This is expected behaviour so far.

```python
from transitions import Machine

m = Machine(states=['A', 'B', 'C'], initial='A', before_state_change='do_stuff')

print(m.state)  # >>> A
try:
    m.to_B()
except AttributeError:
    pass
print(m.state)  # >>> A

m = Machine(states=['A', 'B', 'C'], initial='A', after_state_change='do_stuff')

try:
    m.to_B()
except AttributeError:
    pass
print(m.state)  # >>> B
```

**Comment by aleneum** [comment]
Hi @dgtlmoon,

do you still have issues with the way the library handles exceptions during state transitions? Feel free to leave some feedback/suggestions.

**Comment by aleneum** [comment]
closing this due to inactivity. Feel free to reopen the issue if it still persist.

**Comment by pkonyves** [comment]
Hi there, I was just looking for information on which cases does a 'rollback' occur on state transition when any of the callback raises an exception. Would it be possible to add this information to the main documentation?
Thank you!

**Comment by aleneum** [comment]
> Would it be possible to add this information to the main documentation?

sure thing! I added the passage right after the execution order.

**Comment by pkonyves** [comment]
cool, thank you!
