### ISSUE TITLE
How can I add a callback by passing the function instead of a string

### ISSUE THREAD

**Issue by luminize** [tyarkoni/transitions#205]
Hi, Thank you for your work on this library. It makes implementing state machines a joy!

I would like to implement a callback to a function from outside the class to trigger on the `on_enter_init` callback.

this is part of the code.

```python
class BasicMachine(object):
    states = ['unknown',
            'init',
            'unhomed',
            'homing',
            'homed',
            'active',
            'inactive',
            'error']
    transitions = [
            { 'trigger': 'initialize', 'source': 'unknown', 'dest': 'init' },
            { 'trigger': 'initialized', 'source': 'init', 'dest': 'unhomed' },
            { 'trigger': 'homing_start', 'source': 'unhomed', 'dest': 'homing' },
            { 'trigger': 'homing_done', 'source': 'homing', 'dest': 'homed' },
            { 'trigger': 'start', 'source': 'homed', 'dest': 'active' },
            { 'trigger': 'stop', 'source': 'active', 'dest': 'inactive' } ]

    def __init__(self):
        self.machine = Machine(model=self,
                                states=BasicMachine.states,
                                transitions=BasicMachine.transitions,
                                initial='unknown')

class Joint(object):

    def __init__(self,):
        self.machine = BasicMachine()
        self.setup_callbacks()

    # setup callbacks so that on entering states certain functions are executed
    # make sure the function passed to the callback can be used independantly
    def setup_callbacks(self):
        self.machine.machine.on_enter_init(self.cb_reset_node())

    def cb_reset_node(self):
        print('resetting node')
```

when I call joint.machine.initialize() I get the following error: TypeError: 'NoneType' object is not callable

```Python
joint.machine.initialize()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/transitions/core.py", line 251, in trigger
    return self.machine._process(f)
  File "/usr/local/lib/python2.7/dist-packages/transitions/core.py", line 638, in _process
    return trigger()
  File "/usr/local/lib/python2.7/dist-packages/transitions/core.py", line 276, in _trigger
    if t.execute(event):
  File "/usr/local/lib/python2.7/dist-packages/transitions/core.py", line 177, in execute
    self._change_state(event_data)
  File "/usr/local/lib/python2.7/dist-packages/transitions/core.py", line 188, in _change_state
    event_data.machine.get_state(self.dest).enter(event_data)
  File "/usr/local/lib/python2.7/dist-packages/transitions/core.py", line 62, in enter
    event_data.machine._callback(oe, event_data)
  File "/usr/local/lib/python2.7/dist-packages/transitions/core.py", line 621, in _callback
    func(*event_data.args, **event_data.kwargs)
TypeError: 'NoneType' object is not callable
```
now if I were to add the callback like this:
```python
    def setup_callbacks(self):
        self.machine.machine.on_enter_init(self.cb_reset_node.__func__)
```
I get a missing argument error on the cb_reset_node method.

```python
>>> m.joints[20].machine.initialize()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/transitions/core.py", line 251, in trigger
    return self.machine._process(f)
  File "/usr/local/lib/python2.7/dist-packages/transitions/core.py", line 638, in _process
    return trigger()
  File "/usr/local/lib/python2.7/dist-packages/transitions/core.py", line 276, in _trigger
    if t.execute(event):
  File "/usr/local/lib/python2.7/dist-packages/transitions/core.py", line 177, in execute
    self._change_state(event_data)
  File "/usr/local/lib/python2.7/dist-packages/transitions/core.py", line 188, in _change_state
    event_data.machine.get_state(self.dest).enter(event_data)
  File "/usr/local/lib/python2.7/dist-packages/transitions/core.py", line 62, in enter
    event_data.machine._callback(oe, event_data)
  File "/usr/local/lib/python2.7/dist-packages/transitions/core.py", line 621, in _callback
    func(*event_data.args, **event_data.kwargs)
TypeError: cb_reset_node() takes exactly 1 argument (0 given)
```

Any thoughts on how to properly do this would be highly appreciated.

**Comment by aleneum** [comment]
Hi @luminize,

`on_enter_<state>` expects a function pointer or a name of a model function.

`self.machine.machine.on_enter_init(self.cb_reset_node())` calls  `cb_reset_node` and tries to bind the *result* which is `None` as a callback. This is not callable as the raised Error mentions.

`self.machine.machine.on_enter_init(self.cb_reset_node.__func__)`
In this case you try to pass an *unbound* function which requires an argument (`self`). In unbound functions `self` is not assigned. This is why Pythons complains.

What you need to do is to pass the *bound* method like that:
`self.machine.machine.on_enter_init(self.cb_reset_node)`

**Comment by luminize** [comment]
@aleneum thanks for the help. This was the answer I was looking for. I had not realized the differences between bound and unbound methods (learned somethin I wasn't aware of today). I'm using transitions for an application running Machinekit and canopen package. Python is the glue for all machine logic here :)
Thanks!
