### ISSUE TITLE
Error on passing data to functions in 'before', 'after' and 'conditions'

### ISSUE THREAD

**Issue by harshi3t** [tyarkoni/transitions#46]
The first example in "Passing Data" section in README gives this error:
```
Traceback (most recent call last):
  File "/Users/harshit/PycharmProjects/DialogFlow/test.py", line 17, in <module>
    lump.melt(temp=45, pressure=1853.68)  # keyword args
  File "/usr/local/lib/python3.5/site-packages/transitions/core.py", line 227, in trigger
    if t.execute(event):
  File "/usr/local/lib/python3.5/site-packages/transitions/core.py", line 145, in execute
    machine.callback(getattr(event_data.model, func), event_data)
  File "/usr/local/lib/python3.5/site-packages/transitions/core.py", line 460, in callback
    func(*event_data.args, **event_data.kwargs)
TypeError: print_pressure() got an unexpected keyword argument 'temp'
```
on adding transitions the following way
`machine.add_transition('melt', 'solid', 'liquid', before='set_environment', after='print_pressure')`

**Comment by tyarkoni** [comment]
Please read the whole section. That's expected behavior if your callbacks can't all handle arbitrary args and kwargs, unless you set send_event=True in the Machine initializer. Use the second example.

**Comment by harshi3t** [comment]
Adding transitions in the way defined above in the second example gives the following error:
```
Traceback (most recent call last):
  File "/Users/harshit/PycharmProjects/DialogFlow/Transitions/test.py", line 24, in <module>
    lump.melt(temp=45, pressure=1853.68)  # keyword args
  File "/usr/local/lib/python2.7/site-packages/transitions/core.py", line 227, in trigger
    if t.execute(event):
  File "/usr/local/lib/python2.7/site-packages/transitions/core.py", line 145, in execute
    machine.callback(getattr(event_data.model, func), event_data)
  File "/usr/local/lib/python2.7/site-packages/transitions/core.py", line 458, in callback
    func(event_data)
TypeError: print_pressure() takes exactly 1 argument (2 given)
```
